theme: minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: rock54.net
description: まんが家フカホリユウキのWebサイト

show_downloads: false
site.google_analytics:

site.lang: "ja-JP"
